name: CI-CD Blue Green ECS (OIDC)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 828411126532
  ECR_REPO: ecs-bluegreen-app
  ECS_CLUSTER: ecs-bluegreen-cluster
  ECS_SERVICE_GREEN: green-service
  ECS_SERVICE_BLUE: blue-service
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assume AWS Role (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::828411126532:role/github-actions-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG .

      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPO:$IMAGE_TAG \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Push Docker Image to ECR
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Deploy GREEN Service (Terraform)
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="image_tag=$IMAGE_TAG"

      - name: Scale UP GREEN
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE_GREEN \
            --desired-count 2
